### ISSUE TITLE
Page not found.

### ISSUE THREAD

**Issue by datomnurdin** [lbrendanl/SwiftSwipeView#3]
Your article was not found.

https://medium.com/swift-programming/ios-swipe-view-with-swift-44fa83a2e078

**Comment by LeedleDev** [comment]
Same issue here, anybody got a mirror?

**Comment by lbrendanl** [comment]
Sorry for that! I ended up shutting the blog down, didn't have time to properly maintain it (as you can no doubt tell by me not even getting to these issues until a month late, my apologies).  You aren't missing too much though, it was a drawn out explanation of the code base, but all fairly simple.
